### ISSUE TITLE
Crashes with `invalid literal for int() with base 16: ''` error

### ISSUE THREAD

**Issue by Bamboo-D** [Nikhil-Software-Cartel/TerminalProfileManager#4]
**Description:**

Not sure if this is only happening to me. I'm getting the following error when using Terminal Profile Manager:

```shell
未经处理的异常:  Python.Runtime.PythonException: invalid literal for int() with base 16: ''
   在 Python.Runtime.PythonException.ThrowLastAsClrException()
   在 Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   在 Python.Runtime.Dispatcher.Dispatch(Object[] args)
   在 __System_Threading_ThreadStartDispatcher.Invoke()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
```

This has been bothering me for a long time, and I finally found that modifying line 60 of `main.py` to `background_color='#000000',` can solve the problem. It seems that this is a correct format for setting the black hex code?

**Environment information:**

* Windows 11 22H2 22621.3296
* Miniconda with Python 3.12.2

By the way, I tried Python 3.9.18 (within miniconda), and it works fine too. 

**Thank you for your time and consideration.**

**Comment by nikhil-swamix** [comment]
Dear bamboo, thank you for trying out the program and reporting this issue,
i will replicate with your given py environment, except for windows 11.
Also if you conclude that if changing the color to long hex format fixes
issue on both the runtimes/envs, it would be best to just apply your
suggestion as it increase compatibility . If you would like to make a PR on
that line you are most welcome, since my ETA is atleast 12 hours as im
out of town. Else ill push it once i arrive.
Thanks & Best Regards

**Comment by nikhil-swamix** [comment]
@Bamboo-D can you pull and check if issue fixed? so i may mark for closure, 
regards

**Comment by Bamboo-D** [comment]
Hi @nikhil-swamix 

I pulled the latest code and it worked fine for me.
Thanks for the quick fix!

Best regards
